name: 'Fetch Docker Hub Tags'
description: 'Fetch tag versions of container images published on Docker Hub'
author: 'gperdomor'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  repository:
    description: 'Docker Hub repository name (e.g., "gperdomor/nx-podman" or just "nginx" for official images)'
    required: true
  username:
    description: 'Docker Hub username for authentication (optional for public repos)'
    required: false
  password:
    description: 'Docker Hub password or access token for authentication (optional for public repos)'
    required: false
  max-results:
    description: 'Maximum number of tags to fetch'
    required: false
    default: '200'
  filter:
    description: 'Filter tags using regex pattern (e.g., "^v?[0-9]+\.[0-9]+\.[0-9]+$" for semver only)'
    required: false
    default: ''
  ordering:
    description: 'Ordering of the results (e.g., "last_updated")'
    required: false
    default: 'last_updated'
  name:
    description: 'Name filter for the results (e.g., "alpine")'
    required: false
    default: ''

# Define your outputs here.
outputs:
  tags:
    description: 'Comma-separated list of fetched tags'
  latestTag:
    description: 'The latest tag based on the specified ordering'
  tagCount:
    description: 'Total number of tags fetched'

runs:
  using: node24
  main: dist/index.js
